import { StyleSheet } from 'react-native';

export const C = {
  green: '#16a34a',
  greenLight: '#dcfce7',
  greenMid: '#bbf7d0',
  greenDark: '#166534',
  red: '#dc2626',
  redLight: '#fee2e2',
  redMid: '#fca5a5',
  bg: '#f9fafb',
  white: '#ffffff',
  border: '#e5e7eb',
  borderLight: '#f3f4f6',
  textPrimary: '#111827',
  textSecondary: '#6b7280',
  textMuted: '#9ca3af',
  textDark: '#374151',
} as const;

export const cardShadow = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.06,
  shadowRadius: 4,
  elevation: 2,
} as const;

export const fabShadow = {
  shadowColor: '#16a34a',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.35,
  shadowRadius: 10,
  elevation: 10,
} as const;

export const sharedStyles = StyleSheet.create({
  screenBg: { flex: 1, backgroundColor: '#f9fafb' },
  pageHeader: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  pageTitle: { fontSize: 28, fontWeight: '700', color: '#111827' },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 8,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  fab: {
    position: 'absolute',
    bottom: 28,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#16a34a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 10,
  },
  emptyState: { alignItems: 'center', paddingTop: 80, paddingHorizontal: 32 },
  emptyIcon: { marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: '600', color: '#9ca3af', textAlign: 'center' },
  emptySub: { fontSize: 14, color: '#d1d5db', textAlign: 'center', marginTop: 6 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  badgeGreen: { backgroundColor: '#dcfce7' },
  badgeRed: { backgroundColor: '#fee2e2' },
  badgeText: { fontSize: 13, fontWeight: '600' },
  badgeTextGreen: { color: '#16a34a' },
  badgeTextRed: { color: '#dc2626' },
  saveButton: {
    backgroundColor: '#16a34a',
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
  },
  saveButtonDisabled: { backgroundColor: '#d1d5db' },
  saveButtonText: { fontSize: 17, fontWeight: '700', color: '#ffffff', letterSpacing: 0.5 },
  formLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginTop: 20, marginBottom: 6 },
  formInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    color: '#111827',
  },
});
